#!/usr/bin/env bash
set -euo pipefail

echo "⚙️  1password"

if [[ ! -L ~/.ssh/op-agent.sock ]]; then
	echo "⚡️ Linking 1password agent socket"
	ln -s ~/Library/Group\ Containers/2BUA8C4S2C.com.1password/t/agent.sock ~/.ssh/op-agent.sock
fi
