#!/usr/bin/env bash
set -euo pipefail

# Ask for the administrator password upfront
sudo -v

# Keep-alive: update existing `sudo` time stamp until `.macos` has finished
while true; do
    sudo -n true
    sleep 60
    kill -0 "$$" || exit
done 2>/dev/null &

######################
#  THIRD-PARTY APPS  #
######################

# iTerm2
# ======

# Specify the preferences directory
defaults write com.googlecode.iterm2.plist PrefsCustomFolder -string "$HOME/.iterm/"
# Tell iTerm2 to use the custom preferences in the directory
defaults write com.googlecode.iterm2.plist LoadPrefsFromCustomFolder -bool true
# Saves preferences on quit
defaults write com.googlecode.iterm2 NoSyncNeverRemindPrefsChangesLostForFile_selection 0

# Application
# ===========
