#!/usr/bin/env bash
set -euo pipefail

echo "⚙️  git-repos"

# Dotfiles repository

dotfiles_remote_url=$(chezmoi git -- config --get remote.origin.url)
if [[ $dotfiles_remote_url != "git@*" ]]; then
	echo "⚡️ .dotfiles → Upgrading remote URL to SSH"
	dotfiles_remote_url=$(echo $dotfiles_remote_url | sed 's/https:\/\//git@/' | sed 's/\//:/')
	chezmoi git -- remote set-url origin $dotfiles_remote_url
fi
