{{- if eq .host.os.id "darwin" }}

.oh-my-zsh:
    type: "archive"
    url: "https://github.com/ohmyzsh/ohmyzsh/archive/master.tar.gz"
    exact: true
    stripComponents: 1
    refreshPeriod: "168h"
.zsh/omz/themes/powerlevel10k:
    type: "archive"
    url: "https://github.com/romkatv/powerlevel10k/archive/v1.16.1.tar.gz"
    exact: true
    stripComponents: 1

"{{ .host.paths.font }}/MesloLGS NF Regular.ttf":
    type: "file"
    url: "https://github.com/romkatv/powerlevel10k-media/raw/master/MesloLGS NF Regular.ttf"
    refreshPeriod: "168h"
"{{ .host.paths.font }}/MesloLGS NF Bold.ttf":
    type: "file"
    url: "https://github.com/romkatv/powerlevel10k-media/raw/master/MesloLGS NF Bold.ttf"
    refreshPeriod: "168h"
"{{ .host.paths.font }}/MesloLGS NF Italic.ttf":
    type: "file"
    url: "https://github.com/romkatv/powerlevel10k-media/raw/master/MesloLGS NF Italic.ttf"
    refreshPeriod: "168h"
"{{ .host.paths.font }}/MesloLGS NF Bold Italic.ttf":
    type: "file"
    url: "https://github.com/romkatv/powerlevel10k-media/raw/master/MesloLGS NF Bold Italic.ttf"
    refreshPeriod: "168h"

{{- end }}
