personal:
  name: Ugo Popée
  email: ugo@p0p.ee
  accounts:
    github:
      username: bil0u
      email: github@p0p.ee
    op:
      account: Y5UFKSYDXJED7JQCQGIYRA7B6A
      vault: h66u55hw4da4f5bhbp7fa2ea74

work:
  email: ugo@iliomad.fr
  accounts:
    op:
      account: WIVYUIS6LZHHTIFPIXUWKIUQNU
      vault: ng4vabtt7dxvtdggfphteon5am
      engineering_vault: wgnajbjber6dehxp34r6or4o3m

darwin:
  homebrew:
    taps:
      - homebrew/bundle
      - homebrew/cask
      - homebrew/cask-fonts
      - homebrew/cask-versions
      - homebrew/core
      - bil0u/tap
    formulaes:
      # Utilities
      - bat # Better cat in Terminal
      - cmake # Those that come with macOS are outdated
      - coreutils # Those that come with macOS are outdated
      - curl # Command-line tool for transferring data using various network protocols
      - findutils # Basic directory searching utilities
      - grep # Global Regural Expression Print
      - jq # Lightweight and flexible command-line JSON processor
      - trash # CLI tool that moves files or folder to the trash
      - tree # List contents of directories in a tree-like format
      - unzip # List, test and extract compressed files in a ZIP archive
      - vim # Screen-based text editor program
      - wget # Program that retrieves content from web servers
      - wifi-password # Get current wifi password in terminal
      - mas # Mac AppStore manager
      # Bash / Zsh
      - bash # Latest Bash version
      - bash-completion@2 # Bash in-terminal auto completions
      - zsh # Latest zsh version
      - zsh-completions # Zsh in-terminal auto completions
      # Dev tools
      - asdf # Manage multiple runtime versions with a single CLI tool
      - atmos # Universal Tool for DevOps and Cloud Automation
      - git # Most popular software for distributed version control
      - shellcheck # Static analysis tool that automatically finds bugs in your shell scripts
      - svn # Software versioning and revision control system
    casks:
      # Fonts
      - font-roboto
      - font-inter
      - font-source-code-pro-for-powerline
      - font-source-code-pro
      - font-source-sans-pro
      - font-source-serif-pro
      - font-meslo-for-powerline
      - font-meslo-lg-nerd-font
      - font-meslo-lg
      - font-hack-nerd-font
      # Apps
      - 1password
      - 1password-cli
      - adguard
      - arduino
      - batteries
      - browserosaurus
      - chromedriver
      - discord
      - defaults-edit
      - docker
      - figma
      - firefox
      - google-chrome
      - handbrake
      - iconjar
      - iina
      - iterm2
      - lepton
      - lunar
      - messenger
      - microsoft-auto-update
      - microsoft-word
      - microsoft-excel
      - microsoft-outlook
      - microsoft-powerpoint
      - microsoft-teams
      - nordvpn
      - notion
      - nzbget
      - postman
      - powershell
      - protonmail-bridge
      - shapr3d
      - slack
      - teamviewer
      - the-unarchiver
      - tor-browser
      - transmission
      - utm
      - vanilla
      - visual-studio-code
      - whatsapp
      - xmind
      - zoom
      # Quicklook plugins
      - mdimagesizemdimporter
      - qlmarkdown
      - qlimagesize
      - quicklook-json
  mas:
    - name: "1Password for Safari"
      id: 1569813296
    - name: "Authenticator"
      id: 1538761576
    - name: "Keynote"
      id: 409183694
    - name: "Magnet"
      id: 441258766
    - name: "Numbers"
      id: 409203825
    - name: "Pages"
      id: 409201541
    - name: "Parcel"
      id: 639968404
    - name: "Xcode"
      id: 497799835
  asdf:
    # Languages runtimes
    - name: python
      global: "latest:3.10"
      extra:
        - "latest:3.9"
    - name: nodejs
      global: "latest:16.17"
      extra:
        - "latest:18.8"
    - name: java
      global: "latest:oracle"
    - name: golang
      global: "1.18"
    - name: terraform
    # CLIs
    - name: awscli
    # Tools
    - name: poetry
    - name: pipenv https://github.com/and-semakin/asdf-pipenv.git
  misc:
    go:
      - github.com/catilac/plistwatch@latest
windows:
  cleanup:
    - "*Adobe*"
    - "*Autodesk*"
    - "*BubbleWitch*"
    - "*CandyCrush*"
    - "*Disney*"
    - "*MarchofEmpires*"
    - "*Messenger*"
    - "*Microsoft.549981C3F5F10*"
    - "*Netflix*"
    - "*Plex*"
    - "*PrimeVideo*"
    - "*Spotify*"
    - "*TikTok*"
    - "*Twitter*"
    - Microsoft.*3D*
    - Microsoft.*advertising*
    - Microsoft.Bing*
    - Microsoft.BingFinance
    - Microsoft.BingNews
    - Microsoft.BingSports
    - Microsoft.BingWeather
    - Microsoft.CommsPhone
    - Microsoft.Getstarted
    - Microsoft.Messaging
    - Microsoft.MicrosoftOfficeHub
    - Microsoft.MicrosoftStickyNotes
    - Microsoft.Office.OneNote
    - Microsoft.Office.Sway
    - Microsoft.OneConnect
    - Microsoft.People
    - Microsoft.People
    - Microsoft.SkypeApp
    - Microsoft.Wallet
    - Microsoft.Windows.Photos
    - Microsoft.WindowsAlarms
    - microsoft.windowscommunicationsapps
    - Microsoft.WindowsFeedbackHub
    - Microsoft.WindowsMaps
    - Microsoft.WindowsPhone
    - Microsoft.WindowsSoundRecorder
    - Microsoft.Zune*
  chocolatey:
    # https://docs.chocolatey.org/en-us/create/functions/install-chocolateypackage
    manual:
    # - packageName: test
    #   fileType: msi
    #   url: https://somewhere.com/file.msi
    #   url64bit: https://somewhere.com/file-x64.msi
    #   silentArgs: "/qn /norestart"
    #   validExitCodes: [0, 3010, 1641]
    #   softwareName: Bob*
    #   checksum: "12345"
    #   checksumType: sha256
    #   checksum64: "123356"
    #   checksumType64: sha256
    drivers:
      # - radeon-driver # GPU - AMD Radeon RX 6900XT
      # - intel-network-driver # Network - Intel Ethernet I219-V
      # - intel-wifi-drivers # Wifi - Intel Wireless-AC 9560 160MHz
      # - intel-chipset-drivers # Chipset - Intel Z390 Express
      - intel-graphics-driver # iGPU - Intel UHD 630
      - realtek-hd-audio-driver # Audio - Realtek ALC1220-VB
      - intel-bluetooth-drivers # Bluetooth - Intel Wireless-AC 9560 160MHz
      - samsung-nvme-driver # Storage - Samsung 970 Evo/Pro
    packages:
      # Hardware utilities
      # - amd apps
      # - g-skill lights (RAM) ?
      - nzxt-cam
      - samsung-magician
      # - NuPhy console
      # - foo
      # Monitoring
      - cpu-z
      - gpu-z
      - pci-z
      - ssd-z
      - hwinfo
      # Benchmark
      - aida64-extreme
      - as-ssd
      - cinebench
      - furmark
      - geekbench
      - lanbench
      - occt
      - performancetest
      - prime95
      - heaven-benchmark
      - valley-benchmark
      # System utilities
      - 1password
      - op
      - 7zipcj
      - boxstarter
      - chezmoi
      - ddu
      - id: git
        installArguments: /GitAndUnixToolsOnPath /WindowsTerminal
      - malwarebytes
      - nordvpn
      - powertoys
      - protonmailbridge
      - rufus
      - treesizefree.portable
      - windirstat
      - winrar
      # - cleanmypc
      # - display-fusion
      # - adguard
      # - foo
      # Apps
      - chrome
      - discord
      - firefox
      - gamesavemanager
      - itunes
      - notepadplusplus
      - nzbget
      - signal
      - vscode
      # - mailbird
      # - foo
      # Game platforms
      # - ankama
      - battle.net
      - leagueoflegendseuw
      - origin
      - steam-client
      - ubisoft-connect
      # - roblox
      # - foo
      # Standalone Games
      - minecraft
      # - craftopia
      # - ksp-ckan
      # - ksp
      # - foo
  features:
    # - Containers
  registry:
    # Careful here ! There is a special syntax you should know about before changing values.
    # See /docs/registry.md
    HKLM::
      \SOFTWARE:
        \Microsoft:
          \Windows\CurrentVersion\Policies\System:
            ConsentPromptBehaviorAdmin: 5
          \PolicyManager\default\WiFi\AllowAutoConnectToWiFiSenseHotspots:
            value: 0
        \Policies\Microsoft\Windows:
          \system:
            EnableActivityFeed: 0
            PublishUserActivities: 0
            UploadUserActivities: 0
          \DataCollection:
            AllowTelemetry: 0
    HKCU::
      \SOFTWARE:
        \Microsoft\Windows\CurrentVersion:
          \AdvertisingInfo:
            Enabled: 0
          \Explorer\Advanced:
            NavPaneExpandToCurrentFolder: 1
            NavPaneShowAllFolders: 1
            LaunchTo: 1
          \Search:
            BingSearchEnabled: 0
          \AppHost:
            EnableWebContentEvaluation: 0
          \GameDVR:
            AppCaptureEnabled: 0
      \SYSTEM:
        \GameConfigStore:
          GameDVR_Enabled: 0
  # https://docs.chocolatey.org/en-us/create/functions/install-chocolateypinnedtaskbaritem#mainContent
  taskbar:
    # - firefox
    # - discord
    # - signal
    # - steam-client
  # https://docs.chocolatey.org/en-us/create/functions/install-chocolateyshortcut
  shortcuts:
    # - ShortcutFilePath: C:\notepad.lnk
    #   TargetPath: C:\Windows\System32\notepad.exe
    #   WorkingDirectory: C:\
    #   Arguments: C:\test.txt
    #   IconLocation: C:\test.ico
    #   Description: This is the description
  # https://docs.chocolatey.org/en-us/create/functions/install-chocolateyfileassociation
  associations:
    # .nzb: NZBGet.exe
