# - SYNTAX -
#
#   name:    package name
#   exists:  command to run to know if the package is installed
#   install: commands to run to install the package
#   steps:   number of commands in 'install' category
#   update:  command to update the package , 'false' if none
#
#   RESPECT THE INDENTATION !
#
modules:
  - name: 'Homebrew'
    exists: which brew
    install:
      - /bin/bash -c '$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)'
      - brew tap homebrew/cask-fonts
    steps: 2
    update: brew update
    uninstall: /bin/bash -c '$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/uninstall.sh)'
  - name: 'Oh-My-Zsh'
    exists: echo $ZSH | grep oh-my-zsh
    install:
      - chsh -s $(which zsh)
    steps: 1
    update: bash modules/oh-my-zsh/tools/upgrade.sh
    uninstall: bash modules/oh-my-zsh/tools/uninstall.sh

brew:
  packages:
    - 'coreutils'
    - 'wget'
    - 'cmake'
    - 'zsh-completions'
    - 'node'
    - 'python'
    - 'python2'
    - 'git-flow-avh'
    - 'pyenv'
  casks:
    - 'font-hack-nerd-font'
    - 'iterm2'
    - 'jetbrains-toolbox'
    - 'atom'
    - 'visual-studio-code'
    - 'docker'
    - 'postman'
    - 'lepton'
    - 'nordvpn'
    - 'protonmail-bridge'
    - 'discord'
    - 'slack'
    - 'microsoft-teams'
    - 'firefox'
    - 'google-chrome'
    - 'vlc'
    - 'handbrake'
    - 'the-unarchiver'
    - 'teamviewer'
    - 'plex-media-player'
    - 'molotov'
    - 'nzbget'
    - 'transmission'

python:
  packages:
    - 'ipython'
    - 'pipenv'

app_prefs:
  - name: 'iTerm'
    type: plist
    file: prefs/iterm/com.googlecode.iterm2.plist
  - name: 'Xcode'
    type: xcode_data
    file: prefs/xcode/UserData
  - name: 'Xcode'
    type: plist
    file: prefs/xcode/com.apple.dt.Xcode.plist
