# -- USER CONFIG --

PATH="/usr/local/share/python/:$PATH"
export PATH=$HOME/.bin:/usr/local/bin:$PATH
export EDITOR=vim
export LC_ALL=en_US.UTF-8
export LANG=en_US.UTF-8
export DOTFILES_DIR="$HOME/.dotfiles"

# -- ZSH CUSTOM --

export ZSH="$HOME/.oh-my-zsh"
export UPDATE_ZSH_DAYS=7
ZSH_CUSTOM="$HOME/.zsh"
ZSH_THEME="powerlevel9k/powerlevel9k"
COMPLETION_WAITING_DOTS="true"

plugins=(git)

# -- SOURCING OH MY ZSH --

source "$ZSH/oh-my-zsh.sh"
