DOTFILES_DIR="$HOME/.dotfiles"

PATH="/usr/local/share/python/:$PATH"
export PATH=$HOME/.bin:/usr/local/bin:$PATH

# -- ZSH CUSTOM --

export ZSH="$HOME/.oh-my-zsh"
export UPDATE_ZSH_DAYS=7
ZSH_THEME="powerlevel9k/powerlevel9k"
COMPLETION_WAITING_DOTS="true"

plugins=(git)

# -- SOURCING CONFIGS --

for zsh in $(find $DOTFILES_DIR -maxdepth 2 -name '*.zsh');
do
	source $zsh
done

# -- USER CONFIG --

export EDITOR=vim
export LC_ALL=en_US.UTF-8
export LANG=en_US.UTF-8
